const Data = [
  // {
  //   id: 1,
  //   customerid: 1,
  //   name: "ahmad",
  //   deliveryaddres: "543 g-10, Avenue high gt road",
  //   amount: "$249.5",
  //   paymentmethod: "Card",
  //   contact: 234 - 54 - 54,
  //   status: "Pending",
  // },
  // {
  //   id: 2,
  //   customerid: 2,
  //   name: "anas",
  //   deliveryaddres: "543 g-10, Avenue high gt road",
  //   amount: "$249.5",
  //   paymentmethod: "Card",
  //   contact: 234 - 54 - 54,
  //   status: "Pending",
  // },
  // {
  //   id: 3,
  //   customerid: 3,
  //   name: "abdullah",
  //   deliveryaddres: "543 g-10, Avenue high gt road",
  //   amount: "$249.5",
  //   paymentmethod: "Card",
  //   contact: 234 - 54 - 54,
  //   status: "Pending",
  // },
  // {
  //   id: 3,
  //   customerid: 3,
  //   name: "aw enterprise",
  //   deliveryaddres: "543 g-10, Avenue high gt road",
  //   amount: "$249.5",
  //   paymentmethod: "Card",
  //   contact: 234 - 54 - 54,
  //   status: "Pending",
  // },
  // {
  //   id: 3,
  //   customerid: 3,
  //   name: "test me",
  //   deliveryaddres: "543 g-10, Avenue high gt road",
  //   amount: "$249.5",
  //   paymentmethod: "Card",
  //   contact: 234 - 54 - 54,
  //   status: "Pending",
  // },
  // {
  //   id: 3,
  //   customerid: 3,
  //   name: "ahmad",
  //   deliveryaddres: "543 g-10, Avenue high gt road",
  //   amount: "$249.5",
  //   paymentmethod: "Card",
  //   contact: 234 - 54 - 54,
  //   status: "Pending",
  // },
  // {
  //   id: 3,
  //   customerid: 3,
  //   name: "ahmad",
  //   deliveryaddres: "543 g-10, Avenue high gt road",
  //   amount: "$249.5",
  //   paymentmethod: "Card",
  //   contact: 234 - 54 - 54,
  //   status: "Pending",
  // },
  // {
  //   id: 3,
  //   customerid: 3,
  //   name: "ahmad",
  //   deliveryaddres: "543 g-10, Avenue high gt road",
  //   amount: "$249.5",
  //   paymentmethod: "Card",
  //   contact: 234 - 54 - 54,
  //   status: "Pending",
  // },
  // {
  //   id: 1,
  //   customerid: 1,
  //   name: "ahmad",
  //   deliveryaddres: "543 g-10, Avenue high gt road",
  //   amount: "$249.5",
  //   paymentmethod: "Card",
  //   contact: 234 - 54 - 54,
  //   status: "Pending",
  // },
  // {
  //   id: 2,
  //   customerid: 2,
  //   name: "ahmad",
  //   deliveryaddres: "543 g-10, Avenue high gt road",
  //   amount: "$249.5",
  //   paymentmethod: "Card",
  //   contact: 234 - 54 - 54,
  //   status: "Pending",
  // },
  // {
  //   id: 3,
  //   customerid: 3,
  //   name: "ahmad",
  //   deliveryaddres: "543 g-10, Avenue high gt road",
  //   amount: "$249.5",
  //   paymentmethod: "Card",
  //   contact: 234 - 54 - 54,
  //   status: "Pending",
  // },
];
export default Data;
