const couponsdata = [
  {
    id: 1,
    compaignsname: "Ramadan",
    code: "RAMADAN15",
    remainingcoupon: 5,
    totalcoupon: 20,
    expirationdate: "17 Dec 2020",
    creationdate: "17 Dec 2020",
    status: "Active",
  },
  {
    id: 2,
    compaignsname: "Ramadan kareem",
    code: "RAMADAN15",
    remainingcoupon: 10,
    totalcoupon: 20,
    expirationdate: "17 Dec 2020",
    creationdate: "17 Dec 2020",
    status: "Active",
  },
  {
    id: 3,
    compaignsname: "ahmad",
    code: "RAMADAN15",
    remainingcoupon: 15,
    totalcoupon: 20,
    expirationdate: "17 Dec 2020",
    creationdate: "17 Dec 2020",
    status: "Active",
  },
  {
    id: 4,
    compaignsname: "Ramadan Sale",
    code: "RAMADAN15",
    remainingcoupon: 20,
    totalcoupon: 20,
    expirationdate: "17 Dec 2020",
    creationdate: "17 Dec 2020",
    status: "Active",
  },
  {
    id: 5,
    compaignsname: "Ramadan Sale 234",
    code: "RAMADAN15",
    remainingcoupon: 8,
    totalcoupon: 20,
    expirationdate: "17 Dec 2020",
    creationdate: "17 Dec 2020",
    status: "Revoked",
  },
  {
    id: 6,
    compaignsname: "Ramadan Sale",
    code: "RAMADAN15",
    remainingcoupon: 13,
    totalcoupon: 20,
    expirationdate: "17 Dec 2020",
    creationdate: "17 Dec 2020",
    status: "Revoked",
  },
];
export default couponsdata;
